from datetime import timedelta

from airflow import DAG
from airflow.operators.bash_operator import BashOperator
from airflow.utils.dates import datetime
from airflow.utils.dates import timedelta

default_args = {
    'owner': 'mibrahimbila',
    'depends_on_past': False,
    'start_date': datetime(2020, 12, 23),
    'email': ['mibrahimbila@klox.fr'],
    'email_on_failure': False,
    'email_on_retry': False,
    # 'retries': 1,
    # 'retry_delay': timedelta(minutes=5)
}
dag = DAG(
    'dbt_docs_serve',
    default_args=default_args,
    description='++This DAG serves on port 7171 the doc generated by DBT with the help of the DAG << dbt_docs_generate >>.\n Before running this DAG, Run once <<dbt_docs_generate>> to generate at least once the documentations to serve',
    schedule_interval='@once',
)


VIRTUAL_ENV_ACTIVATION = "/home/klox-dev/.venv/bin/activate"
DBT_DIR = "/home/klox-dev/dbt/klox-dev"
CMD_DBT_DOCS_SERVE ="dbt docs serve --port 7171"


dbt_docs_generate = BashOperator(
    task_id='dbt_docs_serve',
    bash_command=""" 
    source {VIRTUAL_ENV_ACTIVATION};
    cd {DBT_DIR} ;
    {CMD};
    """.format(VIRTUAL_ENV_ACTIVATION=VIRTUAL_ENV_ACTIVATION, DBT_DIR=DBT_DIR,CMD=CMD_DBT_DOCS_SERVE),
    dag=dag
)
